version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: population_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: population
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ..
    container_name: sems_app
    depends_on:
      - db
    ports:
      - "8080:8080"
